require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ExertionsController do

  # This should return the minimal set of attributes required to create a valid
  # Exertion. As you add validations to Exertion, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "journal_entry_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ExertionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all exertions as @exertions" do
      exertion = Exertion.create! valid_attributes
      get :index, {}, valid_session
      assigns(:exertions).should eq([exertion])
    end
  end

  describe "GET show" do
    it "assigns the requested exertion as @exertion" do
      exertion = Exertion.create! valid_attributes
      get :show, {:id => exertion.to_param}, valid_session
      assigns(:exertion).should eq(exertion)
    end
  end

  describe "GET new" do
    it "assigns a new exertion as @exertion" do
      get :new, {}, valid_session
      assigns(:exertion).should be_a_new(Exertion)
    end
  end

  describe "GET edit" do
    it "assigns the requested exertion as @exertion" do
      exertion = Exertion.create! valid_attributes
      get :edit, {:id => exertion.to_param}, valid_session
      assigns(:exertion).should eq(exertion)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Exertion" do
        expect {
          post :create, {:exertion => valid_attributes}, valid_session
        }.to change(Exertion, :count).by(1)
      end

      it "assigns a newly created exertion as @exertion" do
        post :create, {:exertion => valid_attributes}, valid_session
        assigns(:exertion).should be_a(Exertion)
        assigns(:exertion).should be_persisted
      end

      it "redirects to the created exertion" do
        post :create, {:exertion => valid_attributes}, valid_session
        response.should redirect_to(Exertion.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved exertion as @exertion" do
        # Trigger the behavior that occurs when invalid params are submitted
        Exertion.any_instance.stub(:save).and_return(false)
        post :create, {:exertion => { "journal_entry_id" => "invalid value" }}, valid_session
        assigns(:exertion).should be_a_new(Exertion)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Exertion.any_instance.stub(:save).and_return(false)
        post :create, {:exertion => { "journal_entry_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested exertion" do
        exertion = Exertion.create! valid_attributes
        # Assuming there are no other exertions in the database, this
        # specifies that the Exertion created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Exertion.any_instance.should_receive(:update_attributes).with({ "journal_entry_id" => "1" })
        put :update, {:id => exertion.to_param, :exertion => { "journal_entry_id" => "1" }}, valid_session
      end

      it "assigns the requested exertion as @exertion" do
        exertion = Exertion.create! valid_attributes
        put :update, {:id => exertion.to_param, :exertion => valid_attributes}, valid_session
        assigns(:exertion).should eq(exertion)
      end

      it "redirects to the exertion" do
        exertion = Exertion.create! valid_attributes
        put :update, {:id => exertion.to_param, :exertion => valid_attributes}, valid_session
        response.should redirect_to(exertion)
      end
    end

    describe "with invalid params" do
      it "assigns the exertion as @exertion" do
        exertion = Exertion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Exertion.any_instance.stub(:save).and_return(false)
        put :update, {:id => exertion.to_param, :exertion => { "journal_entry_id" => "invalid value" }}, valid_session
        assigns(:exertion).should eq(exertion)
      end

      it "re-renders the 'edit' template" do
        exertion = Exertion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Exertion.any_instance.stub(:save).and_return(false)
        put :update, {:id => exertion.to_param, :exertion => { "journal_entry_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested exertion" do
      exertion = Exertion.create! valid_attributes
      expect {
        delete :destroy, {:id => exertion.to_param}, valid_session
      }.to change(Exertion, :count).by(-1)
    end

    it "redirects to the exertions list" do
      exertion = Exertion.create! valid_attributes
      delete :destroy, {:id => exertion.to_param}, valid_session
      response.should redirect_to(exertions_url)
    end
  end

end
