require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LostItemsController do

  # This should return the minimal set of attributes required to create a valid
  # LostItem. As you add validations to LostItem, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LostItemsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all lost_items as @lost_items" do
      lost_item = LostItem.create! valid_attributes
      get :index, {}, valid_session
      assigns(:lost_items).should eq([lost_item])
    end
  end

  describe "GET show" do
    it "assigns the requested lost_item as @lost_item" do
      lost_item = LostItem.create! valid_attributes
      get :show, {:id => lost_item.to_param}, valid_session
      assigns(:lost_item).should eq(lost_item)
    end
  end

  describe "GET new" do
    it "assigns a new lost_item as @lost_item" do
      get :new, {}, valid_session
      assigns(:lost_item).should be_a_new(LostItem)
    end
  end

  describe "GET edit" do
    it "assigns the requested lost_item as @lost_item" do
      lost_item = LostItem.create! valid_attributes
      get :edit, {:id => lost_item.to_param}, valid_session
      assigns(:lost_item).should eq(lost_item)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new LostItem" do
        expect {
          post :create, {:lost_item => valid_attributes}, valid_session
        }.to change(LostItem, :count).by(1)
      end

      it "assigns a newly created lost_item as @lost_item" do
        post :create, {:lost_item => valid_attributes}, valid_session
        assigns(:lost_item).should be_a(LostItem)
        assigns(:lost_item).should be_persisted
      end

      it "redirects to the created lost_item" do
        post :create, {:lost_item => valid_attributes}, valid_session
        response.should redirect_to(LostItem.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lost_item as @lost_item" do
        # Trigger the behavior that occurs when invalid params are submitted
        LostItem.any_instance.stub(:save).and_return(false)
        post :create, {:lost_item => { "name" => "invalid value" }}, valid_session
        assigns(:lost_item).should be_a_new(LostItem)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        LostItem.any_instance.stub(:save).and_return(false)
        post :create, {:lost_item => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lost_item" do
        lost_item = LostItem.create! valid_attributes
        # Assuming there are no other lost_items in the database, this
        # specifies that the LostItem created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        LostItem.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => lost_item.to_param, :lost_item => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested lost_item as @lost_item" do
        lost_item = LostItem.create! valid_attributes
        put :update, {:id => lost_item.to_param, :lost_item => valid_attributes}, valid_session
        assigns(:lost_item).should eq(lost_item)
      end

      it "redirects to the lost_item" do
        lost_item = LostItem.create! valid_attributes
        put :update, {:id => lost_item.to_param, :lost_item => valid_attributes}, valid_session
        response.should redirect_to(lost_item)
      end
    end

    describe "with invalid params" do
      it "assigns the lost_item as @lost_item" do
        lost_item = LostItem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LostItem.any_instance.stub(:save).and_return(false)
        put :update, {:id => lost_item.to_param, :lost_item => { "name" => "invalid value" }}, valid_session
        assigns(:lost_item).should eq(lost_item)
      end

      it "re-renders the 'edit' template" do
        lost_item = LostItem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LostItem.any_instance.stub(:save).and_return(false)
        put :update, {:id => lost_item.to_param, :lost_item => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lost_item" do
      lost_item = LostItem.create! valid_attributes
      expect {
        delete :destroy, {:id => lost_item.to_param}, valid_session
      }.to change(LostItem, :count).by(-1)
    end

    it "redirects to the lost_items list" do
      lost_item = LostItem.create! valid_attributes
      delete :destroy, {:id => lost_item.to_param}, valid_session
      response.should redirect_to(lost_items_url)
    end
  end

end
