require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TripDaysController do

  # This should return the minimal set of attributes required to create a valid
  # TripDay. As you add validations to TripDay, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "day_date" => "2012-11-25" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TripDaysController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all trip_days as @trip_days" do
      trip_day = TripDay.create! valid_attributes
      get :index, {}, valid_session
      assigns(:trip_days).should eq([trip_day])
    end
  end

  describe "GET show" do
    it "assigns the requested trip_day as @trip_day" do
      trip_day = TripDay.create! valid_attributes
      get :show, {:id => trip_day.to_param}, valid_session
      assigns(:trip_day).should eq(trip_day)
    end
  end

  describe "GET new" do
    it "assigns a new trip_day as @trip_day" do
      get :new, {}, valid_session
      assigns(:trip_day).should be_a_new(TripDay)
    end
  end

  describe "GET edit" do
    it "assigns the requested trip_day as @trip_day" do
      trip_day = TripDay.create! valid_attributes
      get :edit, {:id => trip_day.to_param}, valid_session
      assigns(:trip_day).should eq(trip_day)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TripDay" do
        expect {
          post :create, {:trip_day => valid_attributes}, valid_session
        }.to change(TripDay, :count).by(1)
      end

      it "assigns a newly created trip_day as @trip_day" do
        post :create, {:trip_day => valid_attributes}, valid_session
        assigns(:trip_day).should be_a(TripDay)
        assigns(:trip_day).should be_persisted
      end

      it "redirects to the created trip_day" do
        post :create, {:trip_day => valid_attributes}, valid_session
        response.should redirect_to(TripDay.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved trip_day as @trip_day" do
        # Trigger the behavior that occurs when invalid params are submitted
        TripDay.any_instance.stub(:save).and_return(false)
        post :create, {:trip_day => { "day_date" => "invalid value" }}, valid_session
        assigns(:trip_day).should be_a_new(TripDay)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TripDay.any_instance.stub(:save).and_return(false)
        post :create, {:trip_day => { "day_date" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested trip_day" do
        trip_day = TripDay.create! valid_attributes
        # Assuming there are no other trip_days in the database, this
        # specifies that the TripDay created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TripDay.any_instance.should_receive(:update_attributes).with({ "day_date" => "2012-11-25" })
        put :update, {:id => trip_day.to_param, :trip_day => { "day_date" => "2012-11-25" }}, valid_session
      end

      it "assigns the requested trip_day as @trip_day" do
        trip_day = TripDay.create! valid_attributes
        put :update, {:id => trip_day.to_param, :trip_day => valid_attributes}, valid_session
        assigns(:trip_day).should eq(trip_day)
      end

      it "redirects to the trip_day" do
        trip_day = TripDay.create! valid_attributes
        put :update, {:id => trip_day.to_param, :trip_day => valid_attributes}, valid_session
        response.should redirect_to(trip_day)
      end
    end

    describe "with invalid params" do
      it "assigns the trip_day as @trip_day" do
        trip_day = TripDay.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TripDay.any_instance.stub(:save).and_return(false)
        put :update, {:id => trip_day.to_param, :trip_day => { "day_date" => "invalid value" }}, valid_session
        assigns(:trip_day).should eq(trip_day)
      end

      it "re-renders the 'edit' template" do
        trip_day = TripDay.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TripDay.any_instance.stub(:save).and_return(false)
        put :update, {:id => trip_day.to_param, :trip_day => { "day_date" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested trip_day" do
      trip_day = TripDay.create! valid_attributes
      expect {
        delete :destroy, {:id => trip_day.to_param}, valid_session
      }.to change(TripDay, :count).by(-1)
    end

    it "redirects to the trip_days list" do
      trip_day = TripDay.create! valid_attributes
      delete :destroy, {:id => trip_day.to_param}, valid_session
      response.should redirect_to(trip_days_url)
    end
  end

end
